# Generated by Django 4.0.5 on 2022-06-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_image_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
